config/routes.rb
Tripod::Application.routes.draw do
  get "profiles/show"
    devise_for :users

    devise_scope :user do
        get "register", to: "devise/registrations#new", as: :register
        get "login", to: "devise/sessions#new", as: :login
        get "logout", to: "devise/sessions#destroy", as: :logout
    end

    resources :blogs

    get "feed", to: "blogs#index", as: :feed
    
    root to: "blogs#index"

    get '/:id', to: 'profiles#show'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	
	belongs_to :user

	validates :title, presence: true

	validates :content, presence: true,
	                    length: {
	                    	minimum: 2
	                    }

	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise 	:database_authenticatable, :registerable,
         	:recoverable, :rememberable, :trackable, :validatable

    validates :first_name , presence: true
    
    validates :last_name , presence: true

    validates :profile_name, 	presence: true,
    							uniqueness: true,
    							format: {
    								with: /\A[a-zA-Z0-9_-]+\z/,
    								message: 'Must be formatted correctly.'
    							}

    has_many :blogs

    def full_name
    	first_name + " " + last_name
    end 

    def gravatar_url
        final_email = email.strip.downcase
        hash = Digest::MD5.hexdigest(final_email)
        "http://gravatar.com/avatar/#{hash}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :profile_name]
  end
  
  def handle_unverified_request
    true
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:name, :title, :content, :user_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  	def show
  		@user = User.find_by_profile_name(params[:id])
  		if @user
  			@blogs = @user.blogs.load
  			render action: :show
  		else
  			render file: 'public/404', status: 404, formats: [:html]
  		end
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(type)
		case type
		when :alert
			"alert-danger"
		when :notice
			"alert-success"
		else
			""
		end
	end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/blogs/_form.html.slim
= form_for (@blog), html: {class: "form-horizontal", role: "form"} do |f|
    .col-sm-12.well
        .form-group
            label.control-label.col-sm-2 for= 'name'
                |User
            .col-sm-8
                = f.select :user_id, User.all.collect {|p| [ p.full_name, p.id ] }
        .form-group
            label.control-label.col-sm-2 for= 'title'
                |Title
            .col-sm-8
                = f.text_field :title, class: "form-control", placeholder: "Rest API"
            label#form-offer-on-error.label.label-danger
        .form-group
            label.control-label.col-sm-2 for= 'content'
                |Content
            .col-sm-8
                = f.text_area :content, class: "form-control", rows: "18", placeholder: "Rest API's design principles"
            label#form-offer-on-error.label.label-danger
        button.btn.btn-success.btn-md.icon-ok type = "submit"  Submit

app/views/blogs/edit.html.slim
= link_to 'Show', @blog
'|
= link_to 'Back', blogs_path

h1 Editing Blog

== render 'form'

app/views/blogs/index.html.slim
.page-header#index
    h1
        | Blogs
    = link_to "Post New Blog", new_blog_path, class: "btn btn-info"
- @blogs.each do |blog|
    .blog
        .row
            .col-md-1
                = image_tag blog.user.gravatar_url
            .col-md-10
                strong
                    = blog.title
                .content
                    = blog.content
                .meta
                    = link_to time_ago_in_words(blog.created_at) + " ago", blog
                    |  
                    - if current_user == blog.user
                        span.admin
                            = link_to "Edit", edit_blog_path(blog)
                            |  | 
                            = link_to "Delete", blog, method: :delete, data: {confirm: "Are you sure?"}
                .user
                    a href="#"
                        = blog.user.full_name

app/views/blogs/new.html.slim
= link_to 'Back', root_path
#new 
	h2	New Blog

== render 'form'

app/views/blogs/show.html.slim
.page-header.well#show
	blockquote
		h3
			= @blog.title.capitalize
	p
		= @blog.content
	p 
		= "By " + @blog.user.full_name
	span.admin
        = link_to "Edit", edit_blog_path(@blog)
        |  | 
        = link_to "Back", root_path

app/views/layouts/application.html.slim
doctype html
html
    head
      	link href="http://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css"
      	link href="http://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css" 
      	link href="http://fonts.googleapis.com/css?family=Nixie One" rel="stylesheet" type="text/css"  
        title Tripod
        = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
        = javascript_include_tag "application", "data-turbolinks-track" => true
        = csrf_meta_tags    
    body
    	nav.navbar.navbar-inverse.navbar-fixed-top role="navigation" 
    		.container
    			.navbar-header
    			  	a.navbar-brand href="#"  
                        | Tripod Blogs
                        sup  Alpha 
    			  	ul.nav.navbar-nav
    			  		li 
    			  			= link_to "All Blogs", feed_path
                    ul.nav.navbar-nav.navbar-right
                        - if user_signed_in?
                            li
                                = link_to current_user.full_name, edit_user_registration_path
                            li
                                = link_to "Log Out", logout_path
                        - else 
                            li
                                = link_to "Register", register_path
                            li
                                = link_to "Sign in", login_path

  	.container#data
        - flash.each do |type, message|
            .alert.alert-dismissable class="#{flash_class type}"
                button.close aria-hidden="true" data-dismiss="alert" type="button"  &times;
                = message

  	    = yield

app/views/profiles/show.html.slim
.page-header
	h1
		= @user.full_name


- if @blogs
	- @blogs.each do |blog|
		.container-fluid.well
			= blog.title
			hr
			= blog.content
			.meta
            	= link_to time_ago_in_words(blog.created_at) + " ago", blog